### PR TITLE
update site rules for artist profile pages

### PR DESCRIPTION
**Pull request by hdk5**
Add new icons, add new domain rules, remove superfluous domain rules automatically handled by `getSiteName`

### CODE REVIEW

**Comment by 7nik** [comment]
I wonder if we can drop all those icon resources by doing something like
```js
const SITE_ICON_FOLDER = "https://raw.githubusercontent.com/danbooru/danbooru/22e1b4d3bf0a8776dbac282f4e3a83d62facc537/public/images/";
function getSiteIconUrl (siteName) {
    return getImage(`${SITE_ICON_FOLDER}${siteName.toLowerCase().replaceAll(/[^\w.]/g, "-")}-logo.png`);
}
const getSiteIconUrlMemoized = _.memoize(getSiteIconUrl, memoizeKey);
```
plus check for the site being in the SITE_RULES.
And adjust the code for the async loading of icons, like in buildPostPreview.

**Comment by hdk5** [comment]
It is possible if icons might not be loaded initially is not an issue. Well, the browser will probably just cache them anyways.

**Comment by 7nik** [comment]
Due to CSP, they won't load on Twitter and a few other sites, and you cannot convert a link to a CSP-friendly one synchronically.

**Comment by hdk5** [comment]
Oh, right, I forgot that Twitter does that. But it should work in either case, yeah. Do however you see best.

Also, forgot to add that I noticed a bit of a mess in the main danbooru repo - there are sites defined both in null and own extractor, and some artist urls on the main instance are not normalized to their most recent normal forms (per `Source::URL.profile_url`). Can't really be arsed to fix those myself, so I'll just let @nonamethanks know.

**Pull request merged**
